### ISSUE TITLE
Folder name suggestion

### ISSUE THREAD

**Issue by atdyer** [FRF-Remote-Sensing/DuneLidar#11]
@hokiespurs 

I noticed you've got a folder called [icpCoregistrationVersion1](https://github.com/FRF-Remote-Sensing/DuneLidar/tree/master/Coregistration/icpCoregistrationVersion1). I think in general it's best to shy away from any naming that implies version, since git itself is taking care of version control. My suggestion would be that since you're already in the Coregistration directory, call this one ICP and put all of your ICP code in there. Thoughts?

**Comment by hokiespurs** [comment]
Yeah good call.  I'll rename something more intuitive.  

Thought behind it was we might have multiple ICP versions.  This ICP algorithm was just downloaded off fileexchange, but we might find a better one we want to use in the future.

**Comment by hokiespurs** [comment]
fixed with commit bf2faa1b21f3cdf804b474fe6be5d21e81f69cb4 on line branch
