### ISSUE TITLE
Data can't be nested when generating NetCDF

### ISSUE THREAD

**Issue by atdyer** [FRF-Remote-Sensing/DuneLidar#13]
@hokiespurs 

So the script that combines our data with the metadata can only see variables at the top level of the structure passed to it. For example, wave gauge data is stored like:
- gauge
  - location
    - stuff here
  - FFT
    - stuff here
  - ts
    - stuff here
  - hs
  - wl
  - etc.

The script can only see location, FFT, ts, hw, wl, but none of the 'stuff here'. Two possible solutions:
  1. Restructure the data so that everything is at the same level
  2. Modify the matlab2netcdf script to do some searching

Thoughts?

**Comment by KateBrodie** [comment]
without having looked at the script at all, my vote would be to modify the
script, not change our data organization.

**Comment by atdyer** [comment]
@KateBrodie @hokiespurs Is this something would could ask ASA to do for us?

**Comment by KateBrodie** [comment]
i talked to mike and he said yup, he felt like that was within their scope
of work of services they will provide for us. Feel free to initiate a
conversation with them!

**Comment by atdyer** [comment]
Perfect! While they're working on that I'll get the metadata and templates for the rest of our products underway.

**Comment by hokiespurs** [comment]
I would prepare them for the fact that we'll have data structures embedded in data structures, and show them what our draft for the data structures is.  But until we have a final data file ready, I'd hold off on having them hardcode anything.  

I'd hate to have our outline show data.foo.tigers=[m,n] , but then have us change it to data.foo.lions=[n,m], and cause them to have to rewrite code.

**Comment by atdyer** [comment]
Well looking at what they've already got, nothing's hard coded. The script is just looking for variable names defined in the template files I'm creating. The issue is that the don't look into any sub-structures for variables. The hard-coding comes when I write the template files, which is easy to change if we decide to change our data.

**Comment by hokiespurs** [comment]
Cool,  Using the command "fieldnames" in a loop should work.  Then they will probably have to use the eval command.  

Awesome, just wanted to make sure the wiki layout wasn't seen as something set in stone yet!
