### ISSUE TITLE
What scope for parameters?  

### ISSUE THREAD

**Issue by hokiespurs** [FRF-Remote-Sensing/DuneLidar#17]
How should we introduce hard coded parameters?  One Large parameter file? hard coded in functions?  What functions should they be hardcoded in? 

**Image Plots**
- axis limits (xlim, ylim, caxis)
- Long term how many scans to plot

**Frame**
- xgrid
- ygrid

**Line**
- down line vector
- virtual wave gauge locations

**Comment by hokiespurs** [comment]
I think we should use a param file.  It could be saved as yyyymmdd-HHMM-ss.param.mat, and be loaded in the same way that the *.rot.mat are saved.  

The workflow would then go
**Master Process**
- Loop to find most recent file
  - Coregister File and save coreg.mat in the yyyymmdd-HHMM-ss data folder
  - **Load Param file and resave it in the yyyymmdd-HHMM-ss data folder
  - Process Line/Frame in parallel
    - While processing, when it needs a parameter it will load it from the param file in the data folder, if it can't find a param file, we can have there be defaults.
    - We'll introduce the loading of data from the param file as high up in scope as makes sense, then the functions beneath it can still be really modular

@atdyer, thoughts?

**Comment by atdyer** [comment]
@hokiespurs 

This sounds viable to me, as long as we make sure there are always defaults available and no functions or scripts rely on variables already being loaded into the matlab workspace.

Plotting functions I think should take a varargin and use [inputParser](http://www.mathworks.com/help/matlab/ref/inputparser-class.html) to look for optional variables. Param files could be loaded in ProcessLinescan and ProcessFramescan.

**Comment by hokiespurs** [comment]
@atdyer 

This is the cleanest way I can think of.  I'm trying to avoid having hard coded things in multiple functions.  So hopefully if we want to change something, we know exactly what file to go to.

The other positive of this workflow, is when we do change parameters, we retain that old parameter file.  In the past we've resorted to commenting out old constants and input parameters, and it got messy.

I'm going to keep this issue open and will reply when I have the details ironed out, that way you and @KateBrodie can give it the yay or nay.

**Comment by atdyer** [comment]
@hokiespurs 

Been thinking some more about this... if you use something like inputParser, you'd have the option to pass a param file *or* specific parameters to a lot of these functions. I'm not sure specifically which functions this could be used in (this is just off the top of my head), but you could use ```varargin``` as an input and then at the start of the function, check for a param file and for specific options. So for example, a function call could look like either of the following:

```matlab
doSomething(required_var_1, required_var_2, 'xlim', [0 10], 'ylim', [0 10]);
```

```matlab
doSomething(required_var_1, required_var_2, 'param_file', '/path/to/param.mat');

So the first one would use the ```xlim``` and ```ylim``` passed in, and the second would load the param.mat file and look for those parameters. If it's done this way, you retain the modularity while making it easier for us to keep all of our parameters organized.

**Comment by hokiespurs** [comment]
@atdyer I like it! I also added two more other options for consideration.  I'm not sure which is best.  

- Option 1: pushes all parsing and param file decoding into the plotting functions
- Option 2: keeps all references to a param file out of the plotting functions.
- Option 3: only passes in a structure preloaded from a param file, so no loading of mat files is done in the plotting functions. 

Note how options 2 and 3 have more code to call the function, but option 1 will have that same code within the plotting functions.  

## Option 1

```matlab
makeLinePlot(yaddayadda,'param_file','param.mat');
```

## Option 2

```matlab
load 'param.mat';
if exist(param.line.lineplot.xlim)
     lineplotxlim=param.line.lineplot.xlim;
     makeLinePlot(yaddayadda,'xlim',lineplotxlim);
else
     makeLinePlot(yaddayadda);
end
```

## Option 3

```matlab
load 'param.mat';
if exist(param.line.lineplot)
     makeLinePlot(yaddayadda,'param',param.line.lineplot);
else
     makeLinePlot(yaddayadda);
end
```

**Comment by hokiespurs** [comment]
@atdyer @KateBrodie, Per our discussions, We all agreed OPTION 1!!
