### ISSUE TITLE
zgrid parameters and efficiency

### ISSUE THREAD

**Issue by hokiespurs** [FRF-Remote-Sensing/DuneLidar#3]
Need to revisit

- How to improve efficiency of gridding code
- what parameters to use for zgrid and zgrid interp
  - how far to interpolate? 
  - dont grid over big Z jumps still?

**Comment by KateBrodie** [comment]
Use roundgridavg1D for:
- zGrid
- aGrid
Use interp1nanthresh (or something like it) for:
- zGridInterp (try 10 m in x and 5 m in z)
- aGridInterp (just interpolate normally then turn points to match nans in zGridInterp)

**Comment by hokiespurs** [comment]
done.

Will need to evaluate the performance of the 10m and 5m thresholds
