### ISSUE TITLE
Add skewness/assymetry to LineScience

### ISSUE THREAD

**Issue by KateBrodie** [FRF-Remote-Sensing/DuneLidar#33]
@hokiespurs 
 - added basic code with this commit cc976ddf72255763e8c9a4e707c0dccb318ea7ef
 - updated [line.science.mat wiki ](https://github.com/FRF-Remote-Sensing/DuneLidar/wiki/line.science.mat) with where to save data

@atdyer how do i correctly link things in wiki pages???? like this?

**Comment by atdyer** [comment]
@KateBrodie, yup! :+1:

**Comment by KateBrodie** [comment]
added to LineScience Branch.
