### ISSUE TITLE
Metadata Filenames

### ISSUE THREAD

**Issue by atdyer** [FRF-Remote-Sensing/DuneLidar#36]
@bobfrat

Is there a specific template we'll be using for netCDF filenames for the various products? I've got the wave gauge scripts finished and am ready to finalize filenames that we'll be sending to FDIF.

**Comment by Bobfrat** [comment]
The file naming convention for wave data goes like this:

For monthly files:
```
FRF-ocean_waves_<sensorID>_<YYYYMM>.nc
```

For the real time incremental files (likely all you'll need)
```
FRF-ocean_waves_<sensorID>_<YYYYMMDD>_<HHmmss>.nc
```
I'm not sure what you guys will decide on for the sensorID, maybe something like lidar001 - lidar005 for each of the stations.

@birdage has some cron jobs running on the CHL server that look for the incremental files and build monthly files from them.

**Comment by birdage** [comment]
@atdyer dont forget to update the metadata with the new sensor/station id! :smile: . we might need to generate the containing dirs, but other than that it should work. we might want to test it locally here before we start pushing the realtime, maybe send some examples after the naming is done

**Comment by atdyer** [comment]
@Bobfrat perfect, thanks :+1: 

@birdage cool, is that just the ```id``` field? I'll work on getting some sample data to you ASAP, should I just email them to you?

**Comment by birdage** [comment]
@atdyer it looks like just id in the metadata, but there is a variable for `station id` that we should have filled out as well, other wise netcdf cdm data type will fail. i think @Bobfrat might of hooked you up already?

**Comment by birdage** [comment]
@atdyer email is fine, they are pretty small.

**Comment by Bobfrat** [comment]
For the variable station_name, we populate it with the ```title``` attribute from the metadata template. The ```sensorID``` for the filename should be same as the ```id``` in the metadata template.

**Comment by atdyer** [comment]
Cool, just talked to Kate and we're going with ```lidarWaveGaugeXXX``` where ```XXX``` is the x-shore location in FRF coordinates

**Comment by birdage** [comment]
sounds good

**Comment by birdage** [comment]
@atdyer how goes it?
