### ISSUE TITLE
Range messes up right below lidar

### ISSUE THREAD

**Issue by hokiespurs** [FRF-Remote-Sensing/DuneLidar#4]
Because range can't be negative, points that are landward of the lidar are mapped as being seaward of the lidar because of how we calculate range.  We need to fix this.  See figure below.

![rmatclipsdune](https://cloud.githubusercontent.com/assets/7690281/9335971/0970cfda-45a5-11e5-8809-c1b8ff7c061f.jpg)

**Comment by hokiespurs** [comment]
From talk with @KateBrodie,

Rmat should be calculated by interpolating data to a linear line.  Each point will be interpolated to the line using the perpendicular distance to that line.  There will then be two variables, downline, and offline.  offline should be on the order of cms.  

With this new workflow, the line that the data is being interpolated to must be an input to the function.
[m b] are then used in the equation y=mx+b to generate the line.

This will fix this issue, and make the R variable more scientifically accurate.  

![2015-08-20 11 22 46](https://cloud.githubusercontent.com/assets/7690281/9387362/318b7b8e-472e-11e5-8e36-621bb23e4de0.jpg)

**Comment by atdyer** [comment]
@hokiespurs @KateBrodie 

For down line distance, will we be adopting the east is positive and west is negative convention? The range filter will need positive/negative values to work properly.

**Comment by hokiespurs** [comment]
Yep, when we define the [m,b] parameters, we'll define 0 downline as beneath the scanner, with negative downline landward (West in FRF), positive downline seaward (East in FRF)

**Comment by atdyer** [comment]
Perfect, I'm gonna close this issue since we've got a good solution now. :+1:
