### ISSUE TITLE
Handle GPS dropouts from RXP data

### ISSUE THREAD

**Issue by atdyer** [FRF-Remote-Sensing/DuneLidar#40]
Can RXPconvert return both internal and GPS time (gonna need to check RiVLib)? Would be great if internal time could be returned when GPS isn't available.

**Comment by hokiespurs** [comment]
@atdyer 

From what I remember... Rivlib has an "or" option for what time to return. Either tgps or tinternal based on a Boolean flag. So you'll have to call readrxp twice for internal time and gps time. 

I didn't see a way to do it other than basically doing the same thing in cpp.  

Maybe RiVLib has improved, or maybe there is a way to do it that I wasn't able to figure out.

**Comment by hokiespurs** [comment]
pseudocode:

``` matlab
if sum(isnan(tGPS))==0 %all data is timestamped with GPS

  %use all GPS time

elseif sum(~isnan(tGPS))==0 %no data is timestamped with GPS

  % use filename datestr as t(1) and use relative tInternal for all data

else %some data is timestamped with GPS

  % All data with good tGPS doesnt change, all data holidays use relative tInternal

end
```

One thought is that for times with no GPS timestamped data, we're relying on the CPU clock to be accurate.  To check how accurate the CPU clock is, or how it's drifting, we can look at previous times when the CPU had GPS, and compare times to calculate an offset that we can then apply to the data.

**Comment by hokiespurs** [comment]
This code was implemented, but will need to be revamped when we rewrite readRXP.
