### ISSUE TITLE
What flag for autoprocessing

### ISSUE THREAD

**Issue by hokiespurs** [FRF-Remote-Sensing/DuneLidar#50]
@atdyer @KateBrodie 
For auto-processing, what flag are we going to use to say "I'm processing this file" or "I've processed this file"

```matlab
while(1)
   dnames=dirname('datapath/',1); %the 1 flag returns folders
   isprocessed=false(1,numel(dnames));
   
   for iDName=1:numel(dnames) %find out which is processed
      isprocessed(iDName)=exist([dnames{iDName} '/flag.txt'])~=0; %%HERE
   end
   
   ind=find(isprocessed==0,'1','last');
   
   masterProcess(dnames{ind});

end

```

Do we want to just call if "processinginfo.txt", and include data about the processing in there? 

Thoughts?

**Comment by atdyer** [comment]
@hokiespurs @KateBrodie 

I like that idea, just have a processinginfo.txt file in each directory after processing has finished. We can include things like processing time and even the SHA hash of the code so that we'll always be able to pull up the exact code used to do the processing.

**Comment by hokiespurs** [comment]
@atdyer @KateBrodie 

Cool.  SHA hash is a really really good idea.

Lets actually make it make processingingo.txt as soon as it starts processing that file.  That way we can be running processing on multiple machines or in multiple threads, and not have 2 machines working on the same file at once.

**Comment by hokiespurs** [comment]
@atdyer implented this in 839e4c3
