### ISSUE TITLE
Masterprocess for loop logic

### ISSUE THREAD

**Issue by hokiespurs** [FRF-Remote-Sensing/DuneLidar#55]
@atdyer 

per discussion with @KateBrodie ,

I added a break to the masterprocess loop so it would jump out of the for loop to look for the most recent folder.  For example, if we had files A,B,C,D,E,F,G. We start processing file G, but during processing file "H" appears.  I think the current logic would process 
G-F-E-D-C-B-A-H
Rather than: 
G-H-F-E-D-C-B-A

I did this in the makeitwork branch, but since all that code is garbage :shit: and we're probably going to throw it out, didn't want my awesome, insightful contribution to get tossed out with the trash, so thought i'd make a note of it here. :+1:

**Comment by atdyer** [comment]
@hokiespurs @KateBrodie 

yup, that was the missing piece. I'm doing all the changes that were made in the makeitwork branch (in a not :hankey: way) in a new branch called bug-fixes. Will be merged and ready to go before lunch today.
